const ROLES = {
	HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
	DOCTOR: "DOCTOR",
	BED_MANAGER: "BED_MANAGER",
	AMBULANCE_DRIVER: "AMBULANCE_DRIVER",
	GOVERNMENT_OFFICIAL: "GOVERNMENT_OFFICIAL",
};

module.exports = ROLES;
